name: Foundry

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Cache Foundry artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            ./cache
            ./out
          key: ${{ runner.os }}-foundry-${{ github.head_ref || github.ref_name }}
          restore-keys: ${{ runner.os }}-foundry-

      - name: Run forge fmt
        run: forge fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Cache Foundry artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            ./cache
            ./out
          key: ${{ runner.os }}-foundry-${{ github.head_ref || github.ref_name }}
          restore-keys: ${{ runner.os }}-foundry-

      - name: Run forge lint
        run: forge lint --deny notes

  sizes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Cache Foundry artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            ./cache
            ./out
          key: ${{ runner.os }}-foundry-${{ github.head_ref || github.ref_name }}
          restore-keys: ${{ runner.os }}-foundry-

      - name: Run forge build
        run: forge build --force --sizes

  test:
    needs: sizes
    strategy:
      fail-fast: true
      matrix:
        decimals: [0, 6, 8, 18, 24]
        isolate: [true, false]

    runs-on: ubuntu-latest
    name: "test (${{ matrix.decimals }} decimals, isolate: ${{ matrix.isolate }})"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Cache Foundry artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            ./cache
            ./out
          key: ${{ runner.os }}-foundry-${{ github.head_ref || github.ref_name }}
          restore-keys: ${{ runner.os }}-foundry-

      - name: Run forge tests with a ${{ matrix.decimals }} decimals underlying asset
        run: if [ ${{ matrix.isolate }} = true ]; then forge test -vvv --isolate; else forge test -vvv; fi
        env:
          DECIMALS: ${{ matrix.decimals }}
